// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"calendar/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// NewMockEventUseCase creates a new instance of MockEventUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEventUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEventUseCase {
	mock := &MockEventUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEventUseCase is an autogenerated mock type for the EventUseCase type
type MockEventUseCase struct {
	mock.Mock
}

type MockEventUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEventUseCase) EXPECT() *MockEventUseCase_Expecter {
	return &MockEventUseCase_Expecter{mock: &_m.Mock}
}

// CreateEvent provides a mock function for the type MockEventUseCase
func (_mock *MockEventUseCase) CreateEvent(userID int, dateStr string, title string) (string, error) {
	ret := _mock.Called(userID, dateStr, title)

	if len(ret) == 0 {
		panic("no return value specified for CreateEvent")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int, string, string) (string, error)); ok {
		return returnFunc(userID, dateStr, title)
	}
	if returnFunc, ok := ret.Get(0).(func(int, string, string) string); ok {
		r0 = returnFunc(userID, dateStr, title)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(int, string, string) error); ok {
		r1 = returnFunc(userID, dateStr, title)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEventUseCase_CreateEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateEvent'
type MockEventUseCase_CreateEvent_Call struct {
	*mock.Call
}

// CreateEvent is a helper method to define mock.On call
//   - userID int
//   - dateStr string
//   - title string
func (_e *MockEventUseCase_Expecter) CreateEvent(userID interface{}, dateStr interface{}, title interface{}) *MockEventUseCase_CreateEvent_Call {
	return &MockEventUseCase_CreateEvent_Call{Call: _e.mock.On("CreateEvent", userID, dateStr, title)}
}

func (_c *MockEventUseCase_CreateEvent_Call) Run(run func(userID int, dateStr string, title string)) *MockEventUseCase_CreateEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockEventUseCase_CreateEvent_Call) Return(s string, err error) *MockEventUseCase_CreateEvent_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockEventUseCase_CreateEvent_Call) RunAndReturn(run func(userID int, dateStr string, title string) (string, error)) *MockEventUseCase_CreateEvent_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteEvent provides a mock function for the type MockEventUseCase
func (_mock *MockEventUseCase) DeleteEvent(id string) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteEvent")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEventUseCase_DeleteEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteEvent'
type MockEventUseCase_DeleteEvent_Call struct {
	*mock.Call
}

// DeleteEvent is a helper method to define mock.On call
//   - id string
func (_e *MockEventUseCase_Expecter) DeleteEvent(id interface{}) *MockEventUseCase_DeleteEvent_Call {
	return &MockEventUseCase_DeleteEvent_Call{Call: _e.mock.On("DeleteEvent", id)}
}

func (_c *MockEventUseCase_DeleteEvent_Call) Run(run func(id string)) *MockEventUseCase_DeleteEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockEventUseCase_DeleteEvent_Call) Return(err error) *MockEventUseCase_DeleteEvent_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEventUseCase_DeleteEvent_Call) RunAndReturn(run func(id string) error) *MockEventUseCase_DeleteEvent_Call {
	_c.Call.Return(run)
	return _c
}

// GetEventsForDay provides a mock function for the type MockEventUseCase
func (_mock *MockEventUseCase) GetEventsForDay(userID int, dateStr string) ([]domain.Event, error) {
	ret := _mock.Called(userID, dateStr)

	if len(ret) == 0 {
		panic("no return value specified for GetEventsForDay")
	}

	var r0 []domain.Event
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int, string) ([]domain.Event, error)); ok {
		return returnFunc(userID, dateStr)
	}
	if returnFunc, ok := ret.Get(0).(func(int, string) []domain.Event); ok {
		r0 = returnFunc(userID, dateStr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Event)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int, string) error); ok {
		r1 = returnFunc(userID, dateStr)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEventUseCase_GetEventsForDay_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEventsForDay'
type MockEventUseCase_GetEventsForDay_Call struct {
	*mock.Call
}

// GetEventsForDay is a helper method to define mock.On call
//   - userID int
//   - dateStr string
func (_e *MockEventUseCase_Expecter) GetEventsForDay(userID interface{}, dateStr interface{}) *MockEventUseCase_GetEventsForDay_Call {
	return &MockEventUseCase_GetEventsForDay_Call{Call: _e.mock.On("GetEventsForDay", userID, dateStr)}
}

func (_c *MockEventUseCase_GetEventsForDay_Call) Run(run func(userID int, dateStr string)) *MockEventUseCase_GetEventsForDay_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEventUseCase_GetEventsForDay_Call) Return(events []domain.Event, err error) *MockEventUseCase_GetEventsForDay_Call {
	_c.Call.Return(events, err)
	return _c
}

func (_c *MockEventUseCase_GetEventsForDay_Call) RunAndReturn(run func(userID int, dateStr string) ([]domain.Event, error)) *MockEventUseCase_GetEventsForDay_Call {
	_c.Call.Return(run)
	return _c
}

// GetEventsForMonth provides a mock function for the type MockEventUseCase
func (_mock *MockEventUseCase) GetEventsForMonth(userID int, dateStr string) ([]domain.Event, error) {
	ret := _mock.Called(userID, dateStr)

	if len(ret) == 0 {
		panic("no return value specified for GetEventsForMonth")
	}

	var r0 []domain.Event
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int, string) ([]domain.Event, error)); ok {
		return returnFunc(userID, dateStr)
	}
	if returnFunc, ok := ret.Get(0).(func(int, string) []domain.Event); ok {
		r0 = returnFunc(userID, dateStr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Event)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int, string) error); ok {
		r1 = returnFunc(userID, dateStr)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEventUseCase_GetEventsForMonth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEventsForMonth'
type MockEventUseCase_GetEventsForMonth_Call struct {
	*mock.Call
}

// GetEventsForMonth is a helper method to define mock.On call
//   - userID int
//   - dateStr string
func (_e *MockEventUseCase_Expecter) GetEventsForMonth(userID interface{}, dateStr interface{}) *MockEventUseCase_GetEventsForMonth_Call {
	return &MockEventUseCase_GetEventsForMonth_Call{Call: _e.mock.On("GetEventsForMonth", userID, dateStr)}
}

func (_c *MockEventUseCase_GetEventsForMonth_Call) Run(run func(userID int, dateStr string)) *MockEventUseCase_GetEventsForMonth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEventUseCase_GetEventsForMonth_Call) Return(events []domain.Event, err error) *MockEventUseCase_GetEventsForMonth_Call {
	_c.Call.Return(events, err)
	return _c
}

func (_c *MockEventUseCase_GetEventsForMonth_Call) RunAndReturn(run func(userID int, dateStr string) ([]domain.Event, error)) *MockEventUseCase_GetEventsForMonth_Call {
	_c.Call.Return(run)
	return _c
}

// GetEventsForWeek provides a mock function for the type MockEventUseCase
func (_mock *MockEventUseCase) GetEventsForWeek(userID int, dateStr string) ([]domain.Event, error) {
	ret := _mock.Called(userID, dateStr)

	if len(ret) == 0 {
		panic("no return value specified for GetEventsForWeek")
	}

	var r0 []domain.Event
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int, string) ([]domain.Event, error)); ok {
		return returnFunc(userID, dateStr)
	}
	if returnFunc, ok := ret.Get(0).(func(int, string) []domain.Event); ok {
		r0 = returnFunc(userID, dateStr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Event)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int, string) error); ok {
		r1 = returnFunc(userID, dateStr)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEventUseCase_GetEventsForWeek_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEventsForWeek'
type MockEventUseCase_GetEventsForWeek_Call struct {
	*mock.Call
}

// GetEventsForWeek is a helper method to define mock.On call
//   - userID int
//   - dateStr string
func (_e *MockEventUseCase_Expecter) GetEventsForWeek(userID interface{}, dateStr interface{}) *MockEventUseCase_GetEventsForWeek_Call {
	return &MockEventUseCase_GetEventsForWeek_Call{Call: _e.mock.On("GetEventsForWeek", userID, dateStr)}
}

func (_c *MockEventUseCase_GetEventsForWeek_Call) Run(run func(userID int, dateStr string)) *MockEventUseCase_GetEventsForWeek_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEventUseCase_GetEventsForWeek_Call) Return(events []domain.Event, err error) *MockEventUseCase_GetEventsForWeek_Call {
	_c.Call.Return(events, err)
	return _c
}

func (_c *MockEventUseCase_GetEventsForWeek_Call) RunAndReturn(run func(userID int, dateStr string) ([]domain.Event, error)) *MockEventUseCase_GetEventsForWeek_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateEvent provides a mock function for the type MockEventUseCase
func (_mock *MockEventUseCase) UpdateEvent(id string, userID int, dateStr string, title string) error {
	ret := _mock.Called(id, userID, dateStr, title)

	if len(ret) == 0 {
		panic("no return value specified for UpdateEvent")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, int, string, string) error); ok {
		r0 = returnFunc(id, userID, dateStr, title)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEventUseCase_UpdateEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateEvent'
type MockEventUseCase_UpdateEvent_Call struct {
	*mock.Call
}

// UpdateEvent is a helper method to define mock.On call
//   - id string
//   - userID int
//   - dateStr string
//   - title string
func (_e *MockEventUseCase_Expecter) UpdateEvent(id interface{}, userID interface{}, dateStr interface{}, title interface{}) *MockEventUseCase_UpdateEvent_Call {
	return &MockEventUseCase_UpdateEvent_Call{Call: _e.mock.On("UpdateEvent", id, userID, dateStr, title)}
}

func (_c *MockEventUseCase_UpdateEvent_Call) Run(run func(id string, userID int, dateStr string, title string)) *MockEventUseCase_UpdateEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockEventUseCase_UpdateEvent_Call) Return(err error) *MockEventUseCase_UpdateEvent_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEventUseCase_UpdateEvent_Call) RunAndReturn(run func(id string, userID int, dateStr string, title string) error) *MockEventUseCase_UpdateEvent_Call {
	_c.Call.Return(run)
	return _c
}
