// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"calendar/internal/domain"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockEventRepository creates a new instance of MockEventRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEventRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEventRepository {
	mock := &MockEventRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEventRepository is an autogenerated mock type for the EventRepository type
type MockEventRepository struct {
	mock.Mock
}

type MockEventRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEventRepository) EXPECT() *MockEventRepository_Expecter {
	return &MockEventRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockEventRepository
func (_mock *MockEventRepository) Create(e domain.Event) (string, error) {
	ret := _mock.Called(e)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(domain.Event) (string, error)); ok {
		return returnFunc(e)
	}
	if returnFunc, ok := ret.Get(0).(func(domain.Event) string); ok {
		r0 = returnFunc(e)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(domain.Event) error); ok {
		r1 = returnFunc(e)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEventRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockEventRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - e domain.Event
func (_e *MockEventRepository_Expecter) Create(e interface{}) *MockEventRepository_Create_Call {
	return &MockEventRepository_Create_Call{Call: _e.mock.On("Create", e)}
}

func (_c *MockEventRepository_Create_Call) Run(run func(e domain.Event)) *MockEventRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 domain.Event
		if args[0] != nil {
			arg0 = args[0].(domain.Event)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockEventRepository_Create_Call) Return(s string, err error) *MockEventRepository_Create_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockEventRepository_Create_Call) RunAndReturn(run func(e domain.Event) (string, error)) *MockEventRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockEventRepository
func (_mock *MockEventRepository) Delete(id string) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEventRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockEventRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id string
func (_e *MockEventRepository_Expecter) Delete(id interface{}) *MockEventRepository_Delete_Call {
	return &MockEventRepository_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *MockEventRepository_Delete_Call) Run(run func(id string)) *MockEventRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockEventRepository_Delete_Call) Return(err error) *MockEventRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEventRepository_Delete_Call) RunAndReturn(run func(id string) error) *MockEventRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUserAndRange provides a mock function for the type MockEventRepository
func (_mock *MockEventRepository) GetByUserAndRange(userID int, from time.Time, to time.Time) ([]domain.Event, error) {
	ret := _mock.Called(userID, from, to)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserAndRange")
	}

	var r0 []domain.Event
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int, time.Time, time.Time) ([]domain.Event, error)); ok {
		return returnFunc(userID, from, to)
	}
	if returnFunc, ok := ret.Get(0).(func(int, time.Time, time.Time) []domain.Event); ok {
		r0 = returnFunc(userID, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Event)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int, time.Time, time.Time) error); ok {
		r1 = returnFunc(userID, from, to)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEventRepository_GetByUserAndRange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUserAndRange'
type MockEventRepository_GetByUserAndRange_Call struct {
	*mock.Call
}

// GetByUserAndRange is a helper method to define mock.On call
//   - userID int
//   - from time.Time
//   - to time.Time
func (_e *MockEventRepository_Expecter) GetByUserAndRange(userID interface{}, from interface{}, to interface{}) *MockEventRepository_GetByUserAndRange_Call {
	return &MockEventRepository_GetByUserAndRange_Call{Call: _e.mock.On("GetByUserAndRange", userID, from, to)}
}

func (_c *MockEventRepository_GetByUserAndRange_Call) Run(run func(userID int, from time.Time, to time.Time)) *MockEventRepository_GetByUserAndRange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockEventRepository_GetByUserAndRange_Call) Return(events []domain.Event, err error) *MockEventRepository_GetByUserAndRange_Call {
	_c.Call.Return(events, err)
	return _c
}

func (_c *MockEventRepository_GetByUserAndRange_Call) RunAndReturn(run func(userID int, from time.Time, to time.Time) ([]domain.Event, error)) *MockEventRepository_GetByUserAndRange_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockEventRepository
func (_mock *MockEventRepository) Update(e domain.Event) error {
	ret := _mock.Called(e)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(domain.Event) error); ok {
		r0 = returnFunc(e)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEventRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockEventRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - e domain.Event
func (_e *MockEventRepository_Expecter) Update(e interface{}) *MockEventRepository_Update_Call {
	return &MockEventRepository_Update_Call{Call: _e.mock.On("Update", e)}
}

func (_c *MockEventRepository_Update_Call) Run(run func(e domain.Event)) *MockEventRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 domain.Event
		if args[0] != nil {
			arg0 = args[0].(domain.Event)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockEventRepository_Update_Call) Return(err error) *MockEventRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEventRepository_Update_Call) RunAndReturn(run func(e domain.Event) error) *MockEventRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
